### ISSUE TITLE
events.js:183

### ISSUE THREAD

**Issue by Neuyazvimyi** [fiftysoft/nginx-rtmp-monitoring#12]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn free ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by LexusSpeed03** [comment]
I am getting this same error any thoughts?
