### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by petrichbg** [fiftysoft/nginx-rtmp-monitoring#2]
node server.js
buffer.js:74
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:74:13)
    at new FetchStream (/var/www/galaxy.net-plus.bg/html/node_modules/fetch/lib/fetch.js:41:27)
    at fetchUrl (/var/www/galaxy.net-plus.bg/html/node_modules/fetch/lib/fetch.js:386:23)
    at Timeout._onTimeout (/var/www/galaxy.net-plus.bg/html/server.js:80:3)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

can u help me ?

**Comment by fiftysoft** [comment]
@petrichbg what is config file you using ?

**Comment by petrichbg** [comment]
{
  "site_title":"RTMP Monitoring",
  "http_server_port":9991,
  "rtmp_server_refresh":3000,
  "rtmp_server_timeout":15000,
  "rtmp_server_url":"http://galaxy.net-plus.bg:8000/stat.xml",
  "rtmp_server_stream_url":"rtmp://http://galaxy.net-plus.bg:1935/live/",
  "language":"en",
  "template":"default",
  "version":"1.0.0"
}

**Comment by fiftysoft** [comment]
maybe you need to add stream to your sever your config is ok

**Comment by maddygoround** [comment]
Any solution on this ?

**Comment by Max01010101010101** [comment]
same here

**Comment by GinRyan** [comment]
yes ,same error here.  The url exists, but always showing me 
buffer.js:74
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:74:13)
    at new FetchStream (M:\nginx-rtmp-monitoring\node_modules\fetch\lib\fetch.js:41:27)
    at fetchUrl (M:\nginx-rtmp-monitoring\node_modules\fetch\lib\fetch.js:386:23)
    at Timeout._onTimeout (M:\nginx-rtmp-monitoring\server.js:80:3)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)


My config file is : 

{
  "site_title":"RTMP Monitoring",
  "http_server_port":9991,
  "rtmp_server_refresh":3000,
  "rtmp_server_timeout":15000,
  "rtmp_server_url":"http://localhost/stat.xml",
  "rtmp_server_stream_url":"rtmp://localhost/live/",
  "language":"en",
  "template":"default",
  "version":"1.0.0"
}

url http://localhost/stat.xml and rtmp://localhost/live/ acceptable.

**Comment by RickyRatchet1** [comment]
go to monitor folder and check if they are there # npm -v # node -v
i dont have node but i have nodejs 
so i tried nodejs server.js and it worked

**Comment by RickyRatchet1** [comment]
from monitor folder check for versions # npm -v # node -v
I did not show node however i did show nodejs so
nodejs server.js worked for me
