### ISSUE TITLE
error

### ISSUE THREAD

**Issue by petrichbg** [fiftysoft/nginx-rtmp-monitoring#5]
node server.js
buffer.js:74
      throw new Error(
      ^

Error: If encoding is specified then the first argument must be a string
    at new Buffer (buffer.js:74:13)
    at new FetchStream (/usr/local/nginx/html/node_modules/fetch/lib/fetch.js:41:27)
    at fetchUrl (/usr/local/nginx/html/node_modules/fetch/lib/fetch.js:386:23)
    at Timeout._onTimeout (/usr/local/nginx/html/server.js:80:3)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by hezila** [comment]
@petrichbg try to update the fetch package to v1.1.0
